#!/usr/bin/env python3
import os, sys
import argparse


PROG = 'uptime'


"""
uptime

this is a simple uptime monitor
charles reid
may 2020
"""


def main(sysargs = sys.argv[1:]):

    parser = get_argument_parser(sysargs)

    # Make sure the user provided SOME arguments
    if(len(sys.argv)==1):
        parser.print_help(sys.stderr)
        sys.exit(1)

    # Parse the arguments
    args = parser.parse_args(sysargs)

    work_dir = args.dir

    print("Working directory:")
    print(work_dir)
    print("Searching for directory on disk...")
    if os.path.isdir(work_dir):
        print("Found!")
    else:
        print("Does not exist!")


def get_argument_parser(sysargs):
    parser = argparse.ArgumentParser(prog = PROG)


    required_args = parser.add_argument_group('Required Arguments')
    required_args.add_argument('-d', '--dir', 
            required=True,
            help="""Specify the location on disk of the directory""")

    return parser


if __name__ == '__main__':
    main()


