#!/usr/bin/env python3
import os
import sys
import time
import threading
import requests
import argparse
from tasks import foo, bar

"""
uptime

this is a simple uptime monitor
charles reid
may 2020
"""


PROGRAM = 'uptime'
TARGETS = {
    'https://google.com',
    'http://charlesreid1.com',
    'https://charlesreid1.com'
}
BROKEN = set()


def main():
    t1 = threading.Thread(target = site_up)
    t2 = threading.Thread(target = site_down)
    t1.start()
    t2.start()


def site_status_ok(url):
    print(f"Site is ok: {url}")


def site_status_back(url):
    print(f"Site is back online: {url}")
    BROKEN.remove(url)
    TARGETS.add(url)


def site_status_down(url):
    print(f"Site is down (first notice): {url}")
    TARGETS.remove(url)
    BROKEN.add(url)


def site_status_stilldown(url):
    print(f"Site is down: {url}")


def site_up():
    while True:
        for url in TARGETS:
            try:
                r = requests.get(url)
                code = r.status_code
                if code<400:
                    site_status_ok(url)
                else:
                    site_status_down(url)
            except requests.ConnectionError:
                site_status_down(url)
        # Sleep 1 min before repeating
        time.sleep(60)


def site_down():
    while True:
        # Sleep 15 min before trying again
        time.sleep(900)
        for url in BROKEN:
            try:
                r = requests.get(url)
                code = r.status_code
                if code<400:
                    site_status_back(url)
                else:
                    site_status_stilldown(url)
            except requests.ConnectionError:
                site_status_stilldown(url)


if __name__ == '__main__':
    main()
